### ISSUE TITLE
(bug) hit box npc Scion Of Eternity and discs - The Eye of Eternity (10/25 )

### ISSUE THREAD

**Issue by declart** [blackfrost-server/BlackFrost-Server#5]
This npc almost haven't any kind of hitbox.  they are almost not possible to be killed from melee dps. this is a disadvantage and does not allow the boss to be taken to phase 3 in time to be killed

they should have an huge hitbox, becouse you have to control your disc ( as melee dps ) to kill them.
https://www.youtube.com/watch?v=CEVohONX1Xs there is a video that show as they should work.
also the disc they drop on the ground they have a bug, they didn't fly over the ground to go to kill the Scion of Eternity ( this happen when somone die over the disc ). 

##### CURRENT BEHAVIOUR:
You are not able to hit them, ( npc=30249 ). and the discs they drops have a bug too.

##### STEPS TO REPRODUCE THE PROBLEM:
1. just put the boss on the phase 2 
2. kill the Lords and Scions 
3. try to hit them with melee attack - also try to fly with the disc that the scions drop

##### AC HASH/COMMIT:
 f1b44029c85b9e25318ba84a099b4103e0d98f4e

**Comment by Si1ker** [comment]
@declart Hello I have check the hitbox and those are ok for melee range as expected with different classes. They are killable in melee range.

I will be closing this since after some additional feedback from other players, they state this is not a problem and there is no bug on it. If you have further evidence on it, you can share it with us in the future.

Thanks for the time on the report!
